[project]
name = "hw-ml-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hopsworks[python]==4.2.6",
    "xgboost==2.1.3",
]

[tool.uv.workspace]
members = [
    "feature-engineering",
]
