[project]
name = "feature-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy<2",
    "pandas<2.2",
    "snowflake-connector-python>=3.15.0",
]
